Depend on newest versions of robot(selenium)
datakurre/robotframework-selenium2screenshots pull request #9
Opened 2017-10-24 08:59 UTC by tomgross

This avoids a condition for Python 3 and robotframework-selenium2library has been renamed to robotframework-seleniumlibrary

Note! This might break with other packages still depending on robotframework-selenium2library

2017-10-24 09:41 UTC, datakurre requested changes

2017-10-24 09:41 UTC, datakurre commented on setup.py
> -        "robotframework-selenium2library",
I'm afraid that we still need to keep this dependency, probably as

"robotframework-selenium2library>=3.0.0b1"

Probably in the future we should follow the path of Selenium2Library and create a new package with name robotframework-seleniumscreenshots

2017-10-24 09:41 UTC, datakurre commented
@tomgross I believe we still need to also depend on the latest Selenium2Library. But with that we could probably release these as a new major release to allow breakages.

2017-11-30 19:16 UTC, tomgross commented
@datakurre You are right. I changed the dependency back to selenium2library (version 3).

2017-11-30 20:21 UTC, datakurre approved these changes

2017-11-30 20:21 UTC, merged